Upgrade and clean up legacy code
ocaml-ppx/ppx_deriving pull request #240
Opened 2020-10-27 02:15 UTC by kit-ty-kate

This PR cleans up several things:
* Removes direct dependencies to `result` and `ocaml-migrate-parsetree`. Both were unused.
* Upgrade from `ounit` to the `ounit2` package
* Upgrade to dune 2.7 (which will generate the opam file for us)
* Enable standard dune warnings (+ `-w -9` otherwise it would have taken me days to do this). This allowed me to detect several unused code (notably in the tests), variables and open.

2020-11-03 08:01 UTC, XVilka requested changes

2020-11-03 08:01 UTC, XVilka commented on dune-project
> +    ppx_derivers
I think you can remove `ppx_derivers` safely, since it's unnecessary for the ppxlib-port: https://github.com/ocaml-ppx/ppx_derivers/issues/6

2020-11-25 06:03 UTC, XVilka commented on dune-project
> +    ppx_derivers
I sent a separate PR for this then: https://github.com/ocaml-ppx/ppx_deriving/pull/244

2020-11-25 12:42 UTC, kit-ty-kate commented
Superseded by #246

2020-11-25 12:42 UTC, closed without merging